main: com.perceivedev.papichestcommands.PAPIChestCommands
name: PAPI-ChestCommands
version: 1.0.1
description: A bukkit plugin to allow ChestCommands to use PlaceholderAPI placeholders
author: Rayzr
depend: [PlaceholderAPI]
loadbefore: [ChestCommands]
load: STARTUP